# 部署控制器
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app-deployment
spec:
  replicas: 2 # 我们声明需要同时运行 2 个应用副本以保证高可用
  selector:
    matchLabels:
      app: laravel-web
  template:
    metadata:
      labels:
        app: laravel-app
      spec:
        containers:
          # 主容器：PHP-FPM
          - name: php-fpm
            image: hanzz168/my-php-app:latest
            ports:
              - containerPort: 9000
          # 边车容器 (Sidecar)：Nginx
          - name: nginx
            image: hanzz168/my-nginx-app:latest
            ports:
              - containerPort: 80

