server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    error_log /var/log/nginx/error.log
    access_log /var/log/nginx/access.log

    # 网站运行目录
    root /var/www/html/public;

    # 路由重写规则，Laravel 的核心
    location {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 将 PHP 请求代理到 PHP-FPM 容器
    location ~ \.php$ {
        try_files $uri =404
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # 注意：这里的 php-app 是你 PHP 容器的网络别名
        fastcgi_pass php-app:9000;

        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

}
